// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmK_WDD29fucF_oJW7vmoDf85GizBiOtk',
    appId: '1:338117336307:web:0250de3fddd676c6abeb86',
    messagingSenderId: '338117336307',
    projectId: 'rampguard-wcc',
    authDomain: 'rampguard-wcc.firebaseapp.com',
    storageBucket: 'rampguard-wcc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ8POuLcaFW2eJx_RMH_JXZ4vGsTwCNQw',
    appId: '1:338117336307:android:5f414eafae4220ffabeb86',
    messagingSenderId: '338117336307',
    projectId: 'rampguard-wcc',
    storageBucket: 'rampguard-wcc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh4ddG9q4rK0TIfWk_7VtWya7j3bzRrMc',
    appId: '1:338117336307:ios:95d3cdaa27fb50dcabeb86',
    messagingSenderId: '338117336307',
    projectId: 'rampguard-wcc',
    storageBucket: 'rampguard-wcc.firebasestorage.app',
    iosBundleId: 'com.example.wccAttendanceSystem',
  );
}
